// ─── SESSIONS (للعرض العام) ───────────────────────────────────────────────────
export const SESSIONS = [
    {
        _id: 's1',
        type: 'تدريب شخصي',
        title: 'برنامج بناء القوة العضلية للمبتدئين',
        format: 'online',
        durationHours: 1, durationMinutes: 30,
        availableSeats: 12,
        price: 0,
        rating: 4.9, reviews: 124,
        image: 'https://images.pexels.com/photos/1552252/pexels-photo-1552252.jpeg?auto=compress&cs=tinysrgb&w=600',
        coachId: { _id: 'co2', fullName: 'أمينة تجريبي' },
    },
    {
        _id: 's2',
        type: 'تغذية رياضية',
        title: 'خطة تغذية رياضية لزيادة الكتلة العضلية',
        format: 'online',
        durationHours: 2, durationMinutes: 0,
        availableSeats: 8,
        price: 3500,
        rating: 4.7, reviews: 89,
        image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
        coachId: { _id: 'co1', fullName: 'كريم تجريبي' },
    },
    {
        _id: 's3',
        type: 'كروسفيت',
        title: 'جلسة كروسفيت جماعية مكثفة لحرق الدهون',
        format: 'in-person',
        location: 'الجزائر العاصمة',
        durationHours: 3, durationMinutes: 0,
        availableSeats: 0,
        price: 8000,
        rating: 5.0, reviews: 47,
        image: 'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?auto=compress&cs=tinysrgb&w=600',
        coachId: { _id: 'co1', fullName: 'كريم تجريبي' },
    },
    {
        _id: 's4',
        type: 'يوغا ومرونة',
        title: 'جلسة يوغا واسترخاء لتحسين المرونة الجسدية',
        format: 'online',
        durationHours: 1, durationMinutes: 45,
        availableSeats: 5,
        price: 5500,
        rating: 4.6, reviews: 63,
        image: 'https://images.pexels.com/photos/3822622/pexels-photo-3822622.jpeg?auto=compress&cs=tinysrgb&w=600',
        coachId: { _id: 'co4', fullName: 'سارة تجريبي' },
    },
];

// ─── COURSES (للعرض العام) ────────────────────────────────────────────────────
export const COURSES = [
    {
        _id: 'c1',
        title: 'أساسيات اللياقة البدنية وبناء العادات الرياضية',
        category: 'لياقة بدنية',
        level: 'مبتدئ',
        coachName: 'أمينة تجريبي',
        modules: Array(12).fill(null),
        price: 0,
        hasCertificate: true,
        image: 'https://images.pexels.com/photos/8968046/pexels-photo-8968046.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        _id: 'c2',
        title: 'إتقان تمارين القوة وكمال الأجسام',
        category: 'كمال الأجسام',
        level: 'متوسط',
        coachName: 'كريم تجريبي',
        modules: Array(8).fill(null),
        price: 12000,
        hasCertificate: true,
        image: 'https://images.pexels.com/photos/669580/pexels-photo-669580.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        _id: 'c3',
        title: 'برنامج الجري والتحمل القلبي للمسافات الطويلة',
        category: 'كارديو',
        level: 'متقدم',
        coachName: 'ياسين تجريبي',
        modules: Array(20).fill(null),
        price: 25000,
        hasCertificate: false,
        image: 'https://images.pexels.com/photos/16513597/pexels-photo-16513597.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        _id: 'c4',
        title: 'التغذية الرياضية الذكية وإدارة الوزن',
        category: 'تغذية رياضية',
        level: 'مبتدئ',
        coachName: 'سارة تجريبي',
        modules: Array(10).fill(null),
        price: 9500,
        hasCertificate: true,
        image: 'https://images.pexels.com/photos/34213999/pexels-photo-34213999.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
];

// ─── COACHES ──────────────────────────────────────────────────────────────────
export const COACHES = [
    {
        _id: 'co1',
        userId: 'u1',
        fullName: 'كريم تجريبي',
        coachingName: 'كريم تجريبي',
        specialty: 'مدرب كمال أجسام وتمارين القوة',
        location: 'الجزائر العاصمة',
        experience: 8,
        rating: 4.9,
        reviews: 234,
        isVerified: true,
        avatarColor: 'from-emerald-500 to-teal-400',
    },
    {
        _id: 'co2',
        userId: 'u2',
        fullName: 'أمينة تجريبي',
        coachingName: 'أمينة تجريبي',
        specialty: 'مدربة يوغا ومرونة جسدية',
        location: 'وهران',
        experience: 12,
        rating: 5.0,
        reviews: 189,
        isVerified: true,
        avatarColor: 'from-violet-600 to-purple-400',
    },
    {
        _id: 'co3',
        userId: 'u3',
        fullName: 'ياسين تجريبي',
        coachingName: 'ياسين تجريبي',
        specialty: 'مدرب كروسفيت وتحمل قلبي',
        location: null,
        experience: 6,
        rating: 4.8,
        reviews: 156,
        isVerified: true,
        avatarColor: 'from-teal-600 to-emerald-400',
    },
    {
        _id: 'co4',
        userId: 'u4',
        fullName: 'سارة تجريبي',
        coachingName: 'سارة تجريبي',
        specialty: 'أخصائية تغذية رياضية',
        location: 'قسنطينة',
        experience: 10,
        rating: 4.7,
        reviews: 98,
        isVerified: true,
        avatarColor: 'from-pink-600 to-rose-400',
    },
];

// ─── BOOKINGS ─────────────────────────────────────────────────────────────────
// Format unifié utilisé par CoachBookings ET CoachDashboard (CalendarSection)
// Champs requis :
//   CoachBookings  → _id, name, category, status, date, time, participants,
//                    rawParticipants, capacity, unitPrice, totalPrice
//   CoachDashboard → category, date, time, name, participants, rawParticipants,
//                    capacity, enrolledStudents, totalPrice
export const BOOKINGS = [
    {
        _id: 'b1',
        name: 'برنامج بناء القوة العضلية للمبتدئين',
        category: 'جلسة',
        status: 'نشط',
        date: '2026-06-20',
        time: '10:00 - 11:30',
        participants: '8/15',
        rawParticipants: 8,
        capacity: 15,
        unitPrice: 0,
        totalPrice: 'مجاني',
    },
    {
        _id: 'b2',
        name: 'خطة تغذية رياضية لزيادة الكتلة العضلية',
        category: 'جلسة',
        status: 'قيد الانتظار',
        date: '2026-06-25',
        time: '14:00 - 16:00',
        participants: '12/20',
        rawParticipants: 12,
        capacity: 20,
        unitPrice: 3500,
        totalPrice: 'دج 42,000',
    },
    {
        _id: 'b3',
        name: 'جلسة كروسفيت جماعية مكثفة لحرق الدهون',
        category: 'جلسة',
        status: 'مكتمل',
        date: '2026-05-15',
        time: '09:00 - 12:00',
        participants: '15/15',
        rawParticipants: 15,
        capacity: 15,
        unitPrice: 8000,
        totalPrice: 'دج 120,000',
    },
    {
        _id: 'b4',
        name: 'جلسة يوغا واسترخاء لتحسين المرونة الجسدية',
        category: 'جلسة',
        status: 'ملغي',
        date: '2026-06-05',
        time: '11:00 - 12:45',
        participants: '3/10',
        rawParticipants: 3,
        capacity: 10,
        unitPrice: 5500,
        totalPrice: 'دج 16,500',
    },
    {
        _id: 'b5',
        name: 'أساسيات اللياقة البدنية وبناء العادات الرياضية',
        category: 'برنامج',
        status: 'نشط',
        date: '2026-07-01',
        time: null,
        enrolledStudents: 10,
        capacity: 30,
        unitPrice: 0,
        totalPrice: 'مجاني',
    },
    {
        _id: 'b6',
        name: 'إتقان تمارين القوة وكمال الأجسام',
        category: 'برنامج',
        status: 'قيد الانتظار',
        date: '2026-07-10',
        time: null,
        enrolledStudents: 28,
        capacity: 30,
        unitPrice: 12000,
        totalPrice: 'دج 336,000',
    },
    {
        _id: 'b7',
        name: 'التغذية الرياضية الذكية وإدارة الوزن',
        category: 'برنامج',
        status: 'مكتمل',
        date: '2026-06-08',
        time: null,
        enrolledStudents: 25,
        capacity: 25,
        unitPrice: 9500,
        totalPrice: 'دج 237,500',
    },
];

// ─── FAVORITES ────────────────────────────────────────────────────────────────
export const FAVORITES = [
    {
        id: 'f1',
        type: 'coach',
        title: 'كريم تجريبي',
        instructor: 'مدرب كمال أجسام وتمارين القوة',
        rating: 4.9,
        price: null,
        image: null,
        avatarColor: 'from-emerald-500 to-teal-400',
    },
    {
        id: 'f2',
        type: 'session',
        title: 'برنامج بناء القوة العضلية للمبتدئين',
        instructor: 'أمينة تجريبي',
        rating: 4.9,
        price: 0,
        image: 'https://images.pexels.com/photos/260352/pexels-photo-260352.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        id: 'f3',
        type: 'course',
        title: 'إتقان تمارين القوة وكمال الأجسام',
        instructor: 'كريم تجريبي',
        rating: 4.7,
        price: 12000,
        image: 'https://images.pexels.com/photos/669580/pexels-photo-669580.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        id: 'f4',
        type: 'session',
        title: 'جلسة كروسفيت جماعية مكثفة لحرق الدهون',
        instructor: 'كريم تجريبي',
        rating: 5.0,
        price: 8000,
        image: 'https://images.pexels.com/photos/4162451/pexels-photo-4162451.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
        id: 'f5',
        type: 'coach',
        title: 'سارة تجريبي',
        instructor: 'أخصائية تغذية رياضية',
        rating: 4.7,
        price: null,
        image: null,
        avatarColor: 'from-pink-600 to-rose-400',
    },
];

// ─── NOTIFICATIONS ────────────────────────────────────────────────────────────
export const NOTIFICATIONS = [
    {
        _id: 'n1',
        type: 'booking',
        title: 'تم تأكيد حجزك',
        message: 'تم تأكيد حجزك في جلسة "برنامج بناء القوة العضلية للمبتدئين" مع المدربة أمينة تجريبي.',
        read: false,
        createdAt: '2026-06-13T18:30:00.000Z',
    },
    {
        _id: 'n2',
        type: 'payment',
        title: 'دفعة قيد الانتظار',
        message: 'لديك دفعة بقيمة 3500 DA قيد الانتظار لجلسة التغذية الرياضية.',
        read: false,
        createdAt: '2026-06-13T10:00:00.000Z',
    },
    {
        _id: 'n3',
        type: 'review',
        title: 'رد على تقييمك',
        message: 'قام المدرب كريم تجريبي بالرد على تقييمك.',
        read: true,
        createdAt: '2026-06-10T15:45:00.000Z',
    },
    {
        _id: 'n4',
        type: 'program',
        title: 'برنامج جديد متاح',
        message: 'تمت إضافة برنامج جديد "التغذية الرياضية الذكية وإدارة الوزن" قد يهمك.',
        read: true,
        createdAt: '2026-06-08T09:00:00.000Z',
    },
    {
        _id: 'n5',
        type: 'reminder',
        title: 'تذكير بجلسة قادمة',
        message: 'لديك جلسة "خطة تغذية رياضية لزيادة الكتلة العضلية" بعد يومين.',
        read: false,
        createdAt: '2026-06-12T07:00:00.000Z',
    },
];

// ─── PAYMENTS ─────────────────────────────────────────────────────────────────
export const PAYMENTS = [
    {
        _id: 'p1',
        description: 'دفع جلسة: كروسفيت جماعية مكثفة',
        amount: 8000,
        status: 'paid',
        method: 'baridimob',
        coachId: { _id: 'co1', fullName: 'كريم تجريبي' },
        createdAt: '2026-05-01T10:00:00.000Z',
        notes: '',
    },
    {
        _id: 'p2',
        description: 'دفع جلسة: خطة تغذية رياضية',
        amount: 3500,
        status: 'pending',
        method: 'ccp',
        coachId: { _id: 'co1', fullName: 'كريم تجريبي' },
        createdAt: '2026-06-12T09:30:00.000Z',
        notes: '',
    },
    {
        _id: 'p3',
        description: 'دفع جلسة: يوغا واسترخاء',
        amount: 5500,
        status: 'refunded',
        method: 'transfer',
        coachId: { _id: 'co4', fullName: 'سارة تجريبي' },
        createdAt: '2026-05-28T12:00:00.000Z',
        notes: 'تم الاسترداد بسبب إلغاء الحجز.',
    },
    {
        _id: 'p4',
        description: 'دفع جلسة: بناء القوة العضلية',
        amount: 0,
        status: 'paid',
        method: 'cash',
        coachId: { _id: 'co2', fullName: 'أمينة تجريبي' },
        createdAt: '2026-06-10T08:00:00.000Z',
        notes: 'جلسة مجانية.',
    },
];

// ─── REVIEWS ──────────────────────────────────────────────────────────────────
export const REVIEWS = [
    {
        _id: 'r1',
        coachId: { _id: 'co1', fullName: 'كريم تجريبي' },
        sessionTitle: 'جلسة كروسفيت جماعية مكثفة لحرق الدهون',
        rating: 5,
        comment: 'تجربة رائعة، المدرب كان محترف جدا وأعطاني خطة تدريب واقعية ساعدتني فعلا في تحقيق نتائج ملموسة. أنصح بشدة بهذه الجلسة لكل من يريد حرق الدهون بسرعة.',
        createdAt: '2026-05-16T12:00:00.000Z',
        coachReply: 'شكرا جزيلا على ثقتك، أتمنى لك المزيد من التقدم!',
    },
    {
        _id: 'r2',
        coachId: { _id: 'co2', fullName: 'أمينة تجريبي' },
        sessionTitle: 'برنامج بناء القوة العضلية للمبتدئين',
        rating: 4,
        comment: 'جلسة مفيدة جدا، تعلمت الكثير عن التمارين الصحيحة لتجنب الإصابات.',
        createdAt: '2026-06-11T16:20:00.000Z',
        coachReply: null,
    },
];

// ─── COACH_PROFILE ────────────────────────────────────────────────────────────
// Utilisé par CoachProfile et CoachDashboard
export const COACH_PROFILE = {
    _id: 'co1',
    userId: 'u1',
    fullName: 'كريم تجريبي',
    artisticName: 'كريم تجريبي',
    coachingName: 'كريم تجريبي',
    specialty: 'مدرب كمال أجسام وتمارين القوة',
    location: 'الجزائر العاصمة',
    experience: 8,
    rating: 4.9,
    reviews: 234,
    isVerified: true,
    avatarColor: 'from-emerald-500 to-teal-400',
    email: 'karim.tajribi@fitora.dz',
    phoneNumber: '+213 555 123 456',
    bio: 'مدرب رياضي معتمد متخصص في كمال الأجسام وتمارين القوة مع أكثر من 8 سنوات من الخبرة. ساعدت أكثر من 200 متدرب في بناء أجسامهم وتحقيق أهدافهم الرياضية.',
    website: 'https://karimtajribi.dz',
    instagram: '@karim.tajribi',
    facebook: 'karimtajribi',
    twitter: '@karimtajribi',
    artTypes: ['كمال الأجسام', 'تمارين القوة', 'اللياقة البدنية'],
    services: ['جلسات تدريب فردية', 'جلسات جماعية', 'برامج تحويل جسدي', 'استشارات رياضية'],
};

// ─── EARNINGS ─────────────────────────────────────────────────────────────────
// Utilisé par CoachEarnings et CoachDashboard
export const EARNINGS = {
    stats: {
        totalEarnings: 751500,
        thisMonth: 178000,
        commissionRates: {
            workshop: 15,   // % عمولة الجلسات
            course: 20,     // % عمولة البرامج
        },
    },
    monthly: [
        { month: 'جان', earnings: 95000  },
        { month: 'فيف', earnings: 112000 },
        { month: 'مار', earnings: 88500  },
        { month: 'أفر', earnings: 134000 },
        { month: 'ماي', earnings: 144000 },
        { month: 'جوان', earnings: 178000 },
    ],
    transactions: [
        {
            id: 't1',
            date: '2026-06-20',
            type: 'جلسة',
            item: 'برنامج بناء القوة العضلية للمبتدئين',
            customer: 'أحمد تجريبي',
            amount: 0,
            commission: 0,
            net: 0,
            status: 'مكتمل',
        },
        {
            id: 't2',
            date: '2026-06-18',
            type: 'برنامج',
            item: 'إتقان تمارين القوة وكمال الأجسام',
            customer: 'سلمى تجريبي',
            amount: 12000,
            commission: 2400,
            net: 9600,
            status: 'مكتمل',
        },
        {
            id: 't3',
            date: '2026-06-15',
            type: 'جلسة',
            item: 'خطة تغذية رياضية لزيادة الكتلة العضلية',
            customer: 'يوسف تجريبي',
            amount: 3500,
            commission: 525,
            net: 2975,
            status: 'مكتمل',
        },
        {
            id: 't4',
            date: '2026-06-12',
            type: 'برنامج',
            item: 'التغذية الرياضية الذكية وإدارة الوزن',
            customer: 'نور تجريبي',
            amount: 9500,
            commission: 1900,
            net: 7600,
            status: 'مكتمل',
        },
        {
            id: 't5',
            date: '2026-06-10',
            type: 'جلسة',
            item: 'جلسة كروسفيت جماعية مكثفة لحرق الدهون',
            customer: 'عمر تجريبي',
            amount: 8000,
            commission: 1200,
            net: 6800,
            status: 'مكتمل',
        },
        {
            id: 't6',
            date: '2026-06-05',
            type: 'جلسة',
            item: 'جلسة يوغا واسترخاء لتحسين المرونة الجسدية',
            customer: 'ليلى تجريبي',
            amount: 5500,
            commission: 825,
            net: 4675,
            status: 'قيد الانتظار',
        },
        {
            id: 't7',
            date: '2026-05-28',
            type: 'برنامج',
            item: 'أساسيات اللياقة البدنية وبناء العادات الرياضية',
            customer: 'رياض تجريبي',
            amount: 0,
            commission: 0,
            net: 0,
            status: 'مكتمل',
        },
        {
            id: 't8',
            date: '2026-05-20',
            type: 'جلسة',
            item: 'خطة تغذية رياضية لزيادة الكتلة العضلية',
            customer: 'إيمان تجريبي',
            amount: 3500,
            commission: 525,
            net: 2975,
            status: 'مكتمل',
        },
        {
            id: 't9',
            date: '2026-05-15',
            type: 'برنامج',
            item: 'إتقان تمارين القوة وكمال الأجسام',
            customer: 'كمال تجريبي',
            amount: 12000,
            commission: 2400,
            net: 9600,
            status: 'مكتمل',
        },
        {
            id: 't10',
            date: '2026-05-10',
            type: 'جلسة',
            item: 'جلسة كروسفيت جماعية مكثفة لحرق الدهون',
            customer: 'سارة تجريبي',
            amount: 8000,
            commission: 1200,
            net: 6800,
            status: 'مكتمل',
        },
    ],
};

// ─── COACH_COURSES ────────────────────────────────────────────────────────────
export const COACH_COURSES = [
    {
        _id: 'cc1',
        title: 'أساسيات اللياقة البدنية وبناء العادات الرياضية',
        description: 'برنامج شامل يغطي أساسيات اللياقة البدنية وتقنيات بناء عادات رياضية مستدامة في الحياة اليومية.',
        category: 'لياقة بدنية',
        level: 'مبتدئ',
        type: 'مجانية',
        price: 0,
        duration: '3 سا',
        hasCertificate: true,
        status: 'نشط',
        enrolledStudents: 10,
        confirmedStudents: 10,
        image: 'https://images.pexels.com/photos/8968046/pexels-photo-8968046.jpeg?auto=compress&cs=tinysrgb&w=600',
        finalExamTitle: 'الامتحان النهائي لأساسيات اللياقة',
        passMark: 70,
        finalExamQuestions: [
            { id: 'fq1', text: 'ما هي أول خطوة قبل بدء أي برنامج رياضي؟', answerType: 'mcq', options: ['الإحماء', 'التمدد القوي', 'الرفع الثقيل', 'الجري السريع'], correct: 0 },
        ],
        modules: [
            {
                id: 'm1', title: 'مقدمة في اللياقة البدنية',
                lessons: [
                    { id: 'l1', title: 'ما هي اللياقة البدنية؟', duration: '20 د', content: 'مقدمة شاملة عن مكونات اللياقة البدنية.', contents: [{ id: 'c1', type: 'فيديو', url: 'https://youtube.com', mode: 'url' }] },
                ],
                quiz: { title: 'اختبار الوحدة 1', questions: [{ id: 'q1', text: 'ما هو التعريف الصحيح للياقة البدنية؟', answerType: 'mcq', options: ['القدرة على أداء الأنشطة الجسدية بكفاءة', 'الحفظ', 'التقليد', 'الإبداع'], correct: 0 }] },
            },
        ],
    },
    {
        _id: 'cc2',
        title: 'إتقان تمارين القوة وكمال الأجسام',
        description: 'استراتيجيات متقدمة لبناء الكتلة العضلية وزيادة القوة من خلال تمارين منظمة ومتدرجة.',
        category: 'كمال الأجسام',
        level: 'متوسط',
        type: 'مدفوعة',
        price: 12000,
        duration: '8 سا',
        hasCertificate: true,
        status: 'نشط',
        enrolledStudents: 28,
        confirmedStudents: 25,
        image: 'https://images.pexels.com/photos/669580/pexels-photo-669580.jpeg?auto=compress&cs=tinysrgb&w=600',
        finalExamTitle: 'الامتحان النهائي لكمال الأجسام',
        passMark: 75,
        finalExamQuestions: [
            { id: 'fq1', text: 'ما أفضل وقت للراحة بين مجموعات تمارين القوة؟', answerType: 'mcq', options: ['60-90 ثانية', '5 ثواني', '10 دقائق', 'بدون راحة'], correct: 0 }
        ],
        modules: [
            {
                id: 'm1', title: 'أساسيات التمرين بالأوزان',
                lessons: [
                    { id: 'l1', title: 'أنواع تمارين القوة', duration: '35 د', content: 'أنواع وأساليب تمارين الأوزان الحرة والأجهزة.', contents: [{ id: 'c1', type: 'فيديو', url: 'https://youtube.com', mode: 'url' }] },
                ],
                quiz: { title: 'اختبار أساسيات التمرين', questions: [{ id: 'q1', text: 'ما أهم عنصر في تمارين القوة؟', answerType: 'mcq', options: ['الأداء الصحيح للحركة', 'السرعة', 'الوزن الأقصى دائماً', 'التكرار العشوائي'], correct: 0 }] },
            },
        ],
    },
    {
        _id: 'cc3',
        title: 'التغذية الرياضية الذكية وإدارة الوزن',
        description: 'تعلم كيف تخطط لوجباتك الرياضية وتدير وزنك بذكاء لتحقيق أهدافك في بناء العضلات أو خسارة الدهون.',
        category: 'تغذية رياضية',
        level: 'مبتدئ',
        type: 'مدفوعة',
        price: 9500,
        duration: '5 سا',
        hasCertificate: true,
        status: 'نشط',
        enrolledStudents: 25,
        confirmedStudents: 25,
        image: 'https://images.pexels.com/photos/34213999/pexels-photo-34213999.jpeg?auto=compress&cs=tinysrgb&w=600',
        finalExamTitle: 'الامتحان النهائي للتغذية الرياضية',
        passMark: 60,
        finalExamQuestions: [
            { id: 'fq1', text: 'ما هو دور البروتين في بناء العضلات؟', answerType: 'mcq', options: ['إصلاح وبناء الأنسجة العضلية', 'مصدر طاقة سريع فقط', 'لا علاقة له بالعضلات', 'يقلل الكتلة العضلية'], correct: 0 }
        ],
        modules: [
            {
                id: 'm1', title: 'أساسيات التغذية الرياضية',
                lessons: [
                    { id: 'l1', title: 'كيف تضع خطة وجبات أسبوعية', duration: '30 د', content: 'خطوات عملية لتخطيط الوجبات الرياضية.', contents: [{ id: 'c1', type: 'PDF', url: 'https://example.com/nutrition.pdf', mode: 'url' }] },
                ],
                quiz: { title: 'اختبار التغذية', questions: [{ id: 'q1', text: 'كم تقريباً تحتاج من البروتين يومياً لرياضي نشط؟', answerType: 'mcq', options: ['1.6-2.2 غ لكل كغ من وزن الجسم', '0.2 غ لكل كغ', '10 غ فقط', 'لا حاجة للبروتين'], correct: 0 }] },
            },
        ],
    },
];

// ─── USERS (admin) ────────────────────────────────────────────────────────────
export const USERS = [
    {
        id: 'co1',
        name: 'كريم تجريبي',
        email: 'karim.tajribi@fitora.dz',
        phone: '+213 555 123 456',
        type: 'COACH',
        status: 'نشط',
        joinDate: '2025-09-05T08:00:00.000Z',
        bookings: 0,
    },
    {
        id: 'co2',
        name: 'أمينة تجريبي',
        email: 'amina.tajribi@fitora.dz',
        phone: '+213 661 234 567',
        type: 'COACH',
        status: 'نشط',
        joinDate: '2025-11-20T14:00:00.000Z',
        bookings: 0,
    },
    {
        id: 'co3',
        name: 'ياسين تجريبي',
        email: 'yassine.tajribi@fitora.dz',
        phone: '+213 770 345 678',
        type: 'COACH',
        status: 'معلق',
        joinDate: '2025-12-01T10:00:00.000Z',
        bookings: 0,
    },
    {
        id: 'co4',
        name: 'سارة تجريبي',
        email: 'sara.tajribi@fitora.dz',
        phone: '+213 555 456 789',
        type: 'COACH',
        status: 'نشط',
        joinDate: '2025-10-15T08:00:00.000Z',
        bookings: 0,
    },
    {
        id: 'u1',
        name: 'أحمد تجريبي',
        email: 'ahmed.tajribi@example.com',
        phone: '0555 123 456',
        type: 'CANDIDATE',
        status: 'نشط',
        joinDate: '2026-01-15T09:30:00.000Z',
        bookings: 5,
    },
    {
        id: 'u2',
        name: 'فاطمة تجريبي',
        email: 'fatima.tajribi@example.com',
        phone: '0770 345 678',
        type: 'CANDIDATE',
        status: 'معلق',
        joinDate: '2026-02-10T11:15:00.000Z',
        bookings: 2,
    },
    {
        id: 'u3',
        name: 'يوسف تجريبي',
        email: 'youssef.tajribi@example.com',
        phone: '0661 567 890',
        type: 'CANDIDATE',
        status: 'نشط',
        joinDate: '2026-03-22T16:45:00.000Z',
        bookings: 8,
    },
    {
        id: 'u4',
        name: 'ليلى تجريبي',
        email: 'leila.tajribi@example.com',
        phone: '0555 789 012',
        type: 'CANDIDATE',
        status: 'نشط',
        joinDate: '2026-04-08T13:20:00.000Z',
        bookings: 3,
    },
    {
        id: 'u5',
        name: 'عمر تجريبي',
        email: 'omar.tajribi@example.com',
        phone: '0661 890 123',
        type: 'CANDIDATE',
        status: 'نشط',
        joinDate: '2026-05-01T09:00:00.000Z',
        bookings: 1,
    },
];